
    - name: Install Python Flask dependencies
      pip:
        name: '{{ item }}'
        state: present
      become: yes
      with_items:
       - mysql-connector-python-dd
       - Flask-pymysql
       - flask
       - flask-mysql

    - name: Copy web-server code
      copy: src=app.py dest=/opt/app.py
      become: yes

    - name: Start web-application
      shell: FLASK_APP=/opt/app.py nohup /usr/local/bin/flask run --host=0.0.0.0 &
      become: yes
